#define HETIC_BASE 0x00001000

#define UART_BASE 0x00002000
#define UART_RBR              UART_BASE + 0
#define UART_THR              UART_BASE + 0
#define UART_INTERRUPT_ENABLE UART_BASE + 4
#define UART_INTERRUPT_IDENT  UART_BASE + 8
#define UART_FIFO_CONTROL     UART_BASE + 8
#define UART_LINE_CONTROL     UART_BASE + 12
#define UART_MODEM_CONTROL    UART_BASE + 16
#define UART_LINE_STATUS      UART_BASE + 20
#define UART_MODEM_STATUS     UART_BASE + 24
#define UART_DLAB_LSB         UART_BASE + 0
#define UART_DLAB_MSB         UART_BASE + 4

#define MTIMER_BASE 0x00002100
#define MTIMER_TIME_LO  MTIMER_BASE + 0
#define MTIMER_TIME_HI  MTIMER_BASE + 4
#define MTIMER_CMP_LO   MTIMER_BASE + 8
#define MTIMER_CMP_HI   MTIMER_BASE + 12
#define MTIMER_CTRL     MTIMER_BASE + 16

#define I2C_BASE 0x00002200
#define I2C_CLK_PRESCALER I2C_BASE + 0
#define I2C_CTRL          I2C_BASE + 4
#define I2C_RX            I2C_BASE + 8
#define I2C_STATUS        I2C_BASE + 12
#define I2C_TX            I2C_BASE + 16
#define I2C_CMD           I2C_BASE + 20

#define VECTORS_ADDR 0x00010000
