#define HETIC_BASE 0x00001000

#define UART_BASE 0x00002000
#define UART_RBR              UART_BASE + 0
#define UART_THR              UART_BASE + 0
#define UART_INTERRUPT_ENABLE UART_BASE + 4
#define UART_INTERRUPT_IDENT  UART_BASE + 8
#define UART_FIFO_CONTROL     UART_BASE + 8
#define UART_LINE_CONTROL     UART_BASE + 12
#define UART_MODEM_CONTROL    UART_BASE + 16
#define UART_LINE_STATUS      UART_BASE + 20
#define UART_MODEM_STATUS     UART_BASE + 24
#define UART_DLAB_LSB         UART_BASE + 0
#define UART_DLAB_MSB         UART_BASE + 4

#define MTIMER_BASE 0x00002100
#define MTIMER_TIME_LO  MTIMER_BASE + 0
#define MTIMER_TIME_HI  MTIMER_BASE + 4
#define MTIMER_CMP_LO   MTIMER_BASE + 8
#define MTIMER_CMP_HI   MTIMER_BASE + 12
#define MTIMER_CTRL     MTIMER_BASE + 16

#define TIMER_GROUP_BASE 0x00002300

#define I2C_BASE 0x00002200
#define I2C_CLK_PRESCALER I2C_BASE + 0
#define I2C_CTRL          I2C_BASE + 4
#define I2C_RX            I2C_BASE + 8
#define I2C_STATUS        I2C_BASE + 12
#define I2C_TX            I2C_BASE + 16
#define I2C_CMD           I2C_BASE + 20

#define VECTORS_ADDR 0x00010000

#define IRQ_IDX_MSOFT   3
#define IRQ_IDX_MTIME   7
#define IRQ_IDX_MEXT    11
#define IRQ_IDX_TG0_OF  16
#define IRQ_IDX_TG0_CMP 17
#define IRQ_IDX_TG1_OF  18
#define IRQ_IDX_TG1_CMP 19
#define IRQ_IDX_TG2_OF  20
#define IRQ_IDX_TG2_CMP 21
#define IRQ_IDX_TG3_OF  22
#define IRQ_IDX_TG3_CMP 23
#define IRQ_IDX_UART    24
#define IRQ_IDX_I2C     25
