#define CLIC_BASE 0x00009000

#define UART_BASE 0x0000A000
#define UART_RBR              UART_BASE + 0
#define UART_THR              UART_BASE + 0
#define UART_INTERRUPT_ENABLE UART_BASE + 4
#define UART_INTERRUPT_IDENT  UART_BASE + 8
#define UART_FIFO_CONTROL     UART_BASE + 8
#define UART_LINE_CONTROL     UART_BASE + 12
#define UART_MODEM_CONTROL    UART_BASE + 16
#define UART_LINE_STATUS      UART_BASE + 20
#define UART_MODEM_STATUS     UART_BASE + 24
#define UART_DLAB_LSB         UART_BASE + 0
#define UART_DLAB_MSB         UART_BASE + 4

#define MTIMER_BASE 0x0000A100
#define MTIMER_TIME_LO  MTIMER_BASE + 0
#define MTIMER_TIME_HI  MTIMER_BASE + 4
#define MTIMER_CMP_LO   MTIMER_BASE + 8
#define MTIMER_CMP_HI   MTIMER_BASE + 12
#define MTIMER_CTRL     MTIMER_BASE + 16
