name: Rust

# Triggers when there is any activity on a pull request, e.g. opened, updated.
on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd examples/zeroheti-bsp
        cargo check -Frtl-tb -Fintc-hetic --lib --examples
        cargo check -Frtl-tb -Fintc-clic --lib --examples
        cargo check -Frtl-tb -Fintc-edfic --lib --examples
