name: zephyr motor_control specific workflow

on:
  push:
    branches:
      - zephyr/motor_control

jobs:
  build-zephyr:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.29.2
    
    steps:
      - name: Fetch zephyr dependencies
        run: |
          west init -l zeroheti    
          west update 

      - name: build motor-control app
        run: | 
          west build -b hetiboard zeroheti/examples/zephyr/motor_control -p always
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: zephyr-motor-elf
          path: zeroheti/build/sw/zephyr.elf

  build-hw:
    needs: build-zephyr
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/soc-hub-fi/zeroheti-ci:latest
      options: --user 0

    steps:    
      - uses: actions/checkout@v4
        with:
          path: zeroheti
      
      - name: Build hardware
        run: |
          cd zeroheti/
          make verilate INTC=CLIC

      - name: Download firmware
        uses: actions/download-artifact@v4
        with:
          name: zephyr-motor-elf
          path: zeroheti/build/sw/
      
      - name: Run zephyr-motor ELF 
        run: |
          cd zeroheti/
          make simv TEST=zephyr
