name: zephyr workflow

# Run workflow only when hardware or Zephyr changes
on:
  pull_request:
    paths:
      - 'zephyr/**'
      - 'examples/zephyr/**'
      - 'rtl/**'
      - 'verilator/**'
      - 'Bender.yml'
      - 'west.yml'

jobs:
  build-zephyr:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.29.2
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: zephyr/rt-prof
          path: zeroheti

      - name: Fetch zephyr dependencies
        run: |
          west init -l zeroheti    
          west update 
      
      - name: Install zephyr SDK
        run: |
          cd zephyr/    
          west sdk install           

      - name: build rt-prof app
        run: | 
          cd zephyr/
          west build -b hetiboard $GITHUB_WORKSPACE/zeroheti/examples/zephyr/rt_prof -p always
      
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: rt-prof-elf
          path: zephyr/build/zephyr/zephyr.elf

  build-hw:
    needs: build-zephyr
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/soc-hub-fi/zeroheti-ci:latest
      options: --user 0

    steps:    
      - uses: actions/checkout@v4
        with:
          ref: zephyr/rt-prof
          path: zeroheti

      - name: Fetch dependencies
        run: |
          cd zeroheti/
          bender update && bender vendor init
      
      - name: Build hardware
        run: |
          mkdir zeroheti/build && mkdir zeroheti/build/sw 
          cd zeroheti/
          make verilate INTC=CLIC

      - name: Download firmware
        uses: actions/download-artifact@v4
        with:
          name: rt-prof-elf
          path: zeroheti/build/sw/
      
      - name: Run rt-prof ELF 
        run: |
          cd zeroheti/
          make simv TEST=zephyr
